mkdir -p Annual-Expenditures/raw
mkdir -p Chronic-Absenteeism/raw
mkdir -p Bullying/raw
mkdir -p CMT-CAPT-Science/raw
mkdir -p College-Entrance-and-Persistence/raw
mkdir -p Educator-Demographics/raw
mkdir -p Educator-Qualifications/raw
mkdir -p Student-Enrollment/raw
mkdir -p Five-Year-Graduation-Rates/raw
mkdir -p Four-Year-Graduation-Rates/raw
mkdir -p Incidents/raw
mkdir -p Per-Pupil-Expenditures/raw
mkdir -p Primary-Disability/raw
mkdir -p Revenue-Sources/raw
mkdir -p Sanctions/raw
mkdir -p Special-Education-Expenditures/raw
mkdir -p Staffing-Levels/raw
mkdir -p Suspension-Rates/raw
mkdir -p Time-with-Nondisabled-Peers/raw